#!/usr/bin/env node
/**
 * The embedding map is regenerated by hand, not on every push — the model is a
 * ~1 GB download. That makes one failure mode invisible: add a paper to
 * papers.bib, forget to re-run, and the map silently omits it while looking
 * perfectly fine.
 *
 * This recomputes the source hash and fails the build when it drifts.
 */
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const MAP = 'src/data/viz/embedding-map.json';
if (!existsSync(MAP)) {
  console.error(`✗ ${MAP} is missing — run: python scripts/build_embedding_map.py`);
  process.exit(1);
}

const bibKeys = [...readFileSync('src/data/papers.bib', 'utf8').matchAll(/@\w+\{([^,]+),/g)]
  .map((m) => m[1].trim())
  .sort();

const dirSlugs = (dir) =>
  existsSync(dir)
    ? readdirSync(dir, { withFileTypes: true })
        .filter((e) => e.isDirectory())
        .map((e) => e.name)
        .sort()
    : [];

const fileSlugs = (dir) =>
  existsSync(dir)
    ? readdirSync(dir)
        .filter((f) => f.endsWith('.md') || f.endsWith('.mdx'))
        .map((f) => f.replace(/\.mdx?$/, ''))
        .sort()
    : [];

// Must match source_hash() in scripts/build_embedding_map.py exactly:
// the sorted, NFC-normalised item ids joined by newlines.
const parts = [
  ...bibKeys,
  ...dirSlugs('src/content/blog').map((s) => `post:${s}`),
  ...dirSlugs('src/content/projects').map((s) => `project:${s}`),
  ...fileSlugs('src/content/news').map((s) => `news:${s}`),
]
  .map((s) => s.normalize('NFC'))
  .sort();

const hash = createHash('sha256').update(parts.join('\n')).digest('hex');
const stored = JSON.parse(readFileSync(MAP, 'utf8')).sourceHash;

if (stored !== hash) {
  console.error('\n✗ the embedding map is stale: the corpus changed since it was built.');
  console.error(`    stored: ${stored}`);
  console.error(`    actual: ${hash}`);
  console.error('\n  Regenerate it with:  gh workflow run update-embeddings.yml');
  console.error('  or locally:          .venv/bin/python scripts/build_embedding_map.py\n');
  process.exit(1);
}

console.log(`✓ embedding map is current (${parts.length} source items)`);
